"""
Shared building blocks of the SyN, TVF and SyNGS registration code, re-exported from the
submodules: ``affine`` (rotation / affine modules, ANTs affine parsing), ``grid`` (grid
sampling and composition; physical <-> normalised helpers from ``syntx.spatial``),
``smoothing`` (Gaussian / DST / B-spline field regularisers), ``losses`` (LNCC, Mattes MI,
distance-transform losses), ``jacobian`` (Jacobian determinants), ``inverse`` (inverse
fields, velocity integration), ``optimizers`` (LARS / Adam variants, CFL step helpers),
``pipeline`` (device choice, input normalisation, cache clean-up) and ``utils`` (intensity
normalisation).
"""

from .affine import (
    get_rotation_matrix,
    HierarchicalAffine,
    grid_to_physical_affine_torch,
    physical_to_grid_affine,
    grid_to_physical_affine,
    parse_ants_affine,
    compute_initial_grid,
)
from .grid import (
    grid_sample_bspline_torch,
    AnalyticalGridSample,
    grid_sample_nd,
    compose_grids,
    resize_field,
    sample_field_cf,
    get_physical_grid_torch,
    get_physical_to_normalized_affine,
    physical_to_normalized_fast,
    physical_to_normalized_torch,
    physical_to_normalized_torch_cached,
    prepare_mid_images_and_gradients_torch,
)
from .smoothing import (
    separable_gaussian_filter,
    get_cached_gaussian_kernel_1d,
    apply_sobolev_green_operator,
    apply_dsti_green_operator,
    apply_dsti1_green_operator,
    smooth_displacement_field_dst,
    smooth_displacement_field_bspline,
    apply_bspline_fluid_operator,
    has_antstorch,
    clear_dst_cache,
    clear_dsti_filter_cache,
    get_dst_cache_info,
    get_dsti_cache_info,
    get_boundary_mask,
    CacheInfo,
)
from .losses import (
    AnalyticalLNCC,
    ANTsPseudoLNCC,
    local_ncc_loss_nd,
    b_spline_3,
    mattes_mi_loss_core,
    mattes_mi_loss_nd,
    compute_soft_distance_transform,
    compute_image_distance_transform,
    distance_transform_loss,
)
from .jacobian import (
    _spatial_jacobian_nd,
    compute_jacobian_determinant_nd,
    compute_physical_jacobian_determinant,
    compute_jacobian_hinge_penalty,
)
from .inverse import (
    update_inverse_field_nd_hybrid_lm,
    integrate_time_varying_velocity_field,
    update_inverse_field_nd_anderson,
    update_inverse_field_nd,
    compute_inverse_identity_error_nd,
    calculate_inverse_identity_error,
)
from .optimizers import (
    LARS,
    RegAdam,
    SobolevAdam,
    GaussianAdam,
    get_cfl_max_norm,
    compute_cfl_step,
    check_convergence,
)
from .pipeline import (
    auto_detect_device,
    normalize_and_tensorize,
    cleanup_gpu,
)
from .utils import (
    normalize_tensor,
    normalize_image,
)

__all__ = [
    'get_rotation_matrix',
    'HierarchicalAffine',
    'grid_to_physical_affine_torch',
    'physical_to_grid_affine',
    'grid_to_physical_affine',
    'parse_ants_affine',
    'compute_initial_grid',
    'grid_sample_bspline_torch',
    'AnalyticalGridSample',
    'grid_sample_nd',
    'compose_grids',
    'resize_field',
    'sample_field_cf',
    'get_physical_grid_torch',
    'get_physical_to_normalized_affine',
    'physical_to_normalized_fast',
    'physical_to_normalized_torch',
    'physical_to_normalized_torch_cached',
    'prepare_mid_images_and_gradients_torch',
    'separable_gaussian_filter',
    'get_cached_gaussian_kernel_1d',
    'apply_sobolev_green_operator',
    'apply_dsti_green_operator',
    'apply_dsti1_green_operator',
    'smooth_displacement_field_dst',
    'smooth_displacement_field_bspline',
    'apply_bspline_fluid_operator',
    'has_antstorch',
    'clear_dst_cache',
    'clear_dsti_filter_cache',
    'get_dst_cache_info',
    'get_dsti_cache_info',
    'get_boundary_mask',
    'CacheInfo',
    'AnalyticalLNCC',
    'ANTsPseudoLNCC',
    'local_ncc_loss_nd',
    'b_spline_3',
    'mattes_mi_loss_core',
    'mattes_mi_loss_nd',
    'compute_soft_distance_transform',
    'compute_image_distance_transform',
    'distance_transform_loss',
    '_spatial_jacobian_nd',
    'compute_jacobian_determinant_nd',
    'compute_physical_jacobian_determinant',
    'compute_jacobian_hinge_penalty',
    'update_inverse_field_nd_hybrid_lm',
    'integrate_time_varying_velocity_field',
    'update_inverse_field_nd_anderson',
    'update_inverse_field_nd',
    'compute_inverse_identity_error_nd',
    'calculate_inverse_identity_error',
    'LARS',
    'RegAdam',
    'SobolevAdam',
    'GaussianAdam',
    'get_cfl_max_norm',
    'compute_cfl_step',
    'check_convergence',
    'auto_detect_device',
    'normalize_and_tensorize',
    'cleanup_gpu',
    'normalize_tensor',
    'normalize_image',
]
