import sys, os
os.environ['ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS'] = '1'
sys.path.insert(0, 'src')
import ants
import numpy as np
import syntx
import tempfile

fi = ants.image_read(ants.get_data('r16'))
mi = ants.image_read(ants.get_data('r64'))

fixed_seg = ants.threshold_image(fi, 'Otsu', 3)
reg_ants_affine = ants.registration(fi, mi, 'Affine')

def get_dice(warped_image):
    warped_seg = ants.threshold_image(warped_image, 'Otsu', 3)
    overlap = ants.label_overlap_measures(fixed_seg, warped_seg)
    return float(overlap.loc[overlap['Label'] == 'All', 'MeanOverlap'].values[0])

# Run Syntx SyN
print("Running Syntx SyN...")
reg = syntx.syn(
    fixed=fi, moving=mi, type_of_transform='SyN', backend='pytorch',
    initial_transform=reg_ants_affine['fwdtransforms'],
    affine_iterations=[0], reg_iterations=[100, 100, 100, 50],
    grad_step=0.25, flow_sigma=3.0, elastic_sigma=0.0,
    syn_metric='lncc', lncc_radius=2, inverse_steps=5
)

# 1. Warp generated by the original unflipped displacement field file
orig_warped = reg['warpedmovout']
print(f"Original (unflipped components) Dice: {get_dice(orig_warped):.4f}")

# 2. Let's read the saved displacement field, flip its components, and warp again
fwd_file_orig = reg['fwdtransforms'][0]
disp_img = ants.image_read(fwd_file_orig)
disp_np = disp_img.numpy()

# Flip the components (last dimension) from YX to XY!
disp_np_flipped = disp_np[..., ::-1].copy()

# Save as a new transform
fwd_file_flipped = tempfile.NamedTemporaryFile(suffix='_fwd_flipped.nii.gz', delete=False).name
fwd_img_flipped = ants.from_numpy(
    disp_np_flipped, origin=fi.origin, spacing=fi.spacing, direction=fi.direction, has_components=True
)
ants.image_write(fwd_img_flipped, fwd_file_flipped)

# Apply the flipped transform
flipped_transforms = [fwd_file_flipped] + reg['fwdtransforms'][1:]
warped_flipped = ants.apply_transforms(fixed=fi, moving=mi, transformlist=flipped_transforms)
print(f"Flipped components Dice: {get_dice(warped_flipped):.4f}")

# Clean up
if os.path.exists(fwd_file_flipped):
    os.remove(fwd_file_flipped)
for path in reg['fwdtransforms'] + reg['invtransforms']:
    if os.path.exists(path):
        os.remove(path)
